### ISSUE TITLE
CTD Error

### ISSUE THREAD

**Issue by echoless3484** [albinaask/SEAL#1]
Hey there, got an error, also message me on Discord: "echoless" if you want quicker responses.

Invalid set index 'borderless' (on base: 'null instance') with value of type 'bool'.

**Comment by albinaask** [comment]
Thank you for submitting this. It's the only way for me to get to know about these bugs.

Hmm, how interesting. Does the program execution halt? If so, could you send a printscreen of the debug panel where you see the entire stack trace?

**Comment by albinaask** [comment]
Seem to have been an error by the user in this case after some discord deliberation
