### ISSUE TITLE
[BUG] _update_visuals() offsets SettingsPanel size

### ISSUE THREAD

**Issue by LightTab2** [albinaask/SEAL#12]
**Description:**
When `_update_visuals()` is called, it set the `SettingsPane/VBoxContainer`'s size to be incorrect.

**Expected behavior:**
`SettingsPane/VBoxContainer`s size remains consistent.

**Screenshots:**
![Godot_v4 3-stable_win64_RqBEdGasAO](https://github.com/user-attachments/assets/4788e803-9785-467f-a336-8701de2f8722)

**Additional info:**
* OS: Windows 11
* Godot Version: 4.3
* Commit: #5

**Comment by LightTab2** [comment]
It might be an issue I have introduced or not, can't check it since it's related to `_update_visuals()` and if I revert my changes, I'll get another issue (#4).

It seems that simply commenting this line out fixes it:
```gdscript
func _update_visuals():
	#_setting_container.size.x = size.x
	...
```

I have changed `BoolSettingPainter` and it doesn't seem to break anything. Not sure why this line was written. Do I introduce a bug that I am not aware of by commenting this out?

`BoolSettingPainter` that has `Container Sizing/Horizontal` not set to `Fill` after removing that line:
![image](https://github.com/user-attachments/assets/c9814ee8-47b4-4089-a2d8-0934ec9c3aef)

**Pop up window** seems not affected:
![image](https://github.com/user-attachments/assets/fd4e5e79-5bec-47c4-9009-383b07315e4c)

And `Fill` works like before:
![image](https://github.com/user-attachments/assets/612ab422-51f7-47e1-97c5-ac49eff6d683)

**Comment by albinaask** [comment]
Thank you for your issue report. Definitely something for me to fix this week-end. The _update_visuals() methods have cost me many hours of bug fixing and wrestling with. So I'm not at all surprised that there are so many bugs here. I'll have a good look at it soon, and I'll mark it for 1.1
