### ISSUE TITLE
SearchingBox Ignore Case option

### ISSUE THREAD

**Issue by LightTab2** [albinaask/SEAL#9]
An option to ignore case of the searched option would be nice.

For settings like that:
![image](https://github.com/user-attachments/assets/58e3cb98-25df-4344-acce-7ed775df2c3c)
This is the current behaviour:
![image](https://github.com/user-attachments/assets/56731c92-2266-4ab5-81d5-2a0dfcb307c8)

**Comment by LightTab2** [comment]
I'm working on it

**Comment by albinaask** [comment]
Arrrrg. I could have sworn I wouldn't have fallen for this simple bug. Thanks for finding it and fixing it!
